<ips:template parameters="$form"/>
<div id="elDtProfilerDiffs" class="ipsPadding ipsClearfix" data-ipstoolboxtoyboximages>
    <h2>Image</h2>
    {$form|raw}
    <button class="ipsButton ipsButton_primary ipsButton_verySmall ipsPos_right ipsMargin_bottom:half" data-convert>Convert</button>
    <div id="dl" class="ipsHide ipsType_center">
        <div>
        <a class="ipsButton ipsButton_primary ipsButton_verySmall ipsMargin_bottom:half">Download</a>
        </div>
        <img class="ipsImage ipsImage_thumb">
    </div>
</div>