<ips:template parameters="$form,$uuid"/>
<div class="ipsPadding ipsClearfix" data-ipstoolboxtoyboxuuid>
    {$form|raw}
    <button class="ipsPos_right ipsButton ipsButton_veryVerySmall ipsButton_primary" id="clearuuid">X</button>
    <button class="ipsPos_right ipsButton ipsButton_veryVerySmall ipsButton_primary ipsMargin_right:half" id="generate">Generate</button>
    <div class="ipsMargin_top" id="elUuidContainer">
        {$uuid|raw}
    </div>
</div>