<ips:template parameters="$menu, $menus"/>
<li>
    <a href="{$menu['url']}{{if !isset($menu['subs']) }}_menu" id="{$menu['url']}" data-ipsMenu{{else}}"{{endif}}>
    {lang="$menu['name']"} {{if isset($menus[$menu['id']])}} <i class="fa fa-chevron-down"></i>{{endif}}
    </a>
    {{if isset( $menus[ $menu['id'] ] ) }}
    <ul id="{$menu['url']}_menu" class="ipsMenu ipsHide ipsClearfix">

        {{foreach $menus[ $menu['id'] ] as $m }}
            {{if isset($m['label'])}}
            <li class="ipsMenu_item ipsMenu_subItems">
                <a href="#apps_{$m['id']}_menu" id="apps_{$m['id']}" data-ipsmenu>{$m['title']}</a>
                <ul id="apps_{$m['id']}_menu" class="ipsMenu ipsHide">
                    {{foreach $menus['subs'][$m['id']] as $mm}}
                    <li class="ipsMenu_item">
                        <a href="{$mm['url']}">{lang="$mm['name']"}</a>
                    </li>
                    {{endforeach}}
                    {{unset($menus['subs'][$m['id']]);}}
                </ul>
            </li>
            {{else}}

            <li class="ipsMenu_item">
                {{if $m['id'] === 'proxy'}}
                <a href="#" data-ipstoolboxproxy>{lang="$m['name']"}</a>
                {{else}}
                <a href="{$m['url']}">{lang="$m['name']"}</a>
                {{endif}}
            </li>
            {{endif}}
        {{endforeach}}
    </ul>
    {{endif}}
</li>
