<ips:template parameters="$time, $memory, $files, $templates, $database, $cache, $logs, $extra, $info, $environment, $debug, $executions"/>
<div id="dtProfilerBarContainer" class="dtProfilerBar">
    <ul class="ipsList_reset dtProfilerBar_list ipsClearfix" data-ipsdtprofiler{{if settings.dtprofiler_enable_debug && settings.dtprofiler_enable_debug_ajax }} data-ipsdtprofilerdebug data-url="{url='app=toolbox&module=bt&controller=bt' base='front'}"{{endif}}>
        {{if $time }}
        <li id="elProfileTimeLog" title="total time" class="isParent dtProfileFirst dtProfilerTime" data-ipstooltip>
            <i class="fa fa-server"></i> {$time['total']}ms <i class="fa fa-angle-up dtprofilearrow"></i>
        </li>
        <ul id="elProfileTimeLog_list" class="ipsList_reset ipsHide dtProfilerBar_cache">
            <li>
                <a>
                    Complete Execution: {$time['total']}ms
                </a>
            </li>
            <li>
                <a>
                    Framework Execution: {$time['framework']}ms
                </a>
            </li>
            <li>
                <a>
                    Profiler Execution: {$time['profiler']}ms
                </a>
            </li>
        </ul>
        {{endif}}

        {{if $executions }}
        {$executions|raw}
        {{endif}}

        {{if $memory }}
        {$memory|raw}
        {{endif}}

        {{if $files }}
        {$files|raw}
        {{endif}}

        {{if $database }}
        {$database|raw}
        {{endif}}

        {{if $cache }}
        {$cache|raw}
        {{endif}}

        {{if $environment }}
        {$environment|raw}
        {{endif}}

        {{if $templates }}
        {$templates|raw}
        {{endif}}

        {{if $logs }}
        {$logs|raw}
        {{endif}}




            {{if isset( $info['sources']) }}
<li class="isParent dtProfileFirst">
            <a id="elProfileSources" href="#elProfileSources_menu" title="Sources" class=" " data-ipstooltip data-ipsmenu>
                Sources <i class="fa fa-angle-up"></i>
            </a>
            <ul id="elProfileSources_menu" class="ipsMenu ipsMenu_auto ipsMenu_wide ipsList_reset ipsHide">
                {{foreach $info['sources'] as $key => $val }}
                <li class="ipsMenu_item">
                     <a href="{$val['url']}" data-ipsDialog data-ipsDialog-destructOnClos="true">
                         {$val['name']}
                     </a>
                </li>
                {{endforeach}}
            </ul>
</li>
            {{endif}}

        <li class="isParent dtProfileFirst celProfileSystem">
            <a id="elProfileSystem" href="#elProfileSystem_menu" title="System" data-ipstooltip data-ipsmenu>
                <i class="fa fa-smile-o"></i> Toy Box <i class="fa fa-angle-up"></i>
            </a>
            <div id="elProfileSystem_menu" class="ipsMenu ipsMenu_wide ipsHide">
                <div class="ipsMenu_title">
                    Generators
                </div>
                <div class="ipsMenu_innerContent">
                    <div class="ipsGrid">
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=lorem' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="Lorem Ipsum Generator">
                                <i class="fa fa-language"></i>
                                <br>
                                Lorem Ipsum
                            </a>
                        </div>
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=bitwiseValues' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="BitWise Generator">
                                <i class="fa">♾️</i>
                                <br>
                                BitWise
                            </a>
                        </div>
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=hash' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="Hash Generator">
                                <i class="fa fa-hashtag"></i>
                                <br>
                                Hash
                            </a>
                        </div>
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=uuid' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="UUID Generator">
                                <i class="fa">✳️</i>
                                <br>
                                UUID
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ipsMenu_title">
                    Encoders/Decoders
                </div>
                <div class="ipsMenu_innerContent">
                    <div class="ipsGrid">
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=html' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="HTML Encoder/Decoder">
                                <i class="fa fa-html5"></i>
                                <br>
                                Html
                            </a>
                        </div>
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=base' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="Base64 Encoder/Decoder">
                                <i class="fa">6️⃣4️⃣</i>
                                <br>
                                Base64
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ipsMenu_title">
                    Converters
                </div>
                <div class="ipsMenu_innerContent">
                    <div class="ipsGrid">
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=numbers' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="Numbers Converters">
                                <i class="fa fa-calculator"></i>
                                <br>
                                Numbers
                            </a>
                        </div>
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=dates' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="Dates Converters">
                                <i class="fa fa-calendar"></i>
                                <br>
                                Dates
                            </a>
                        </div>
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=images' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="Image Converter">
                                <i class="fa fa-image"></i>
                                <br>
                                Images
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ipsMenu_title">
                    System
                </div>
                <div class="ipsMenu_innerContent">
                    <div class="ipsGrid">
                        {{foreach $info['server'] as $key => $val }}
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            {{if $key === 'IPS'}}
                            <i class="fa">🅘🅟🅢</i>
                            <br>
                            {{elseif $key === 'MySql'}}
                            <i class="fa">🅜🅨🅢🅠🅛</i>
                            <br>
                            {{endif}}
                            {$val|raw}
                        </div>
                        {{endforeach}}
                    </div>
                </div>

                <div class="ipsMenu_title">
                    Other
                </div>
                <div class="ipsMenu_innerContent">
                    <div class="ipsGrid">

                        {{$myApps = \defined('DT_MY_APPS') ? explode(',',DT_MY_APPS) : [];}}
                        {{if empty($myApps) === false}}
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=build' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="Build My Apps">
                                <i class="fa fa-compass"></i>
                                <br>
                                Build My Apps
                            </a>
                        </div>
                        {{endif}}
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{url='app=toolbox&module=bt&controller=bt&do=diffs' base='front'}" data-ipsDialog data-ipsDialog-forceReload="true" data-ipsdialog-title="Compare 2 sources">
                                <i class="fa fa-compass"></i>
                                <br>
                                Diffs
                            </a>
                        </div>
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="{$info['cache']}">
                                <i class="fa fa-remove"></i>
                                <br>
                                Clear Caches
                            </a>
                        </div>
                        <div class="ipsGrid_span3 ipsType_center ipsType_bold ipsPadding:half">
                            <a href="#" data-ipstoolboxproxy>
                                <i class="fa">🔃</i>
                                <br>
                                Proxy Class
                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </li>
        {{if \IPS\Settings::i()->dtprofiler_use_console }}
        <li id="elProfileConsoleLog" class="isParent dtProfileFirst dtProfilerConsole">
            <i class="fa fa-terminal"></i> Console
            (<span class="dtprofilerCount" data-count="0">0</span>)
            <i class="fa fa-angle-up dtprofilearrow"></i>
        </li>
        <ul id="elProfileConsoleLog_list" class="ipsList_reset ipsHide dtProfilerBar_generic dtProfilerMaxWidth">
            <li class="notme ipsClearfix">
                Console Log <div class="dtProfilerClearConsoleLog ipsCursor_default ipsPos_right" data-clear> Clear </div>
            </li>
        </ul>
        {{endif}}
        {{if $debug }}
        {$debug|raw}
        {{endif}}

        {{if $extra }}
        {$extra|raw}
        {{endif}}
    </ul>
    {{if $info }}
    <div class="dtProfilerInfoBar">
        {{foreach $info['other'] as $key => $inf }}
        <div>{$key} : {$inf|raw}</div>
        {{endforeach}}

        {{if settings.dtprofiler_git_data || settings.dtprofiler_show_changes}}
        <div id="el_dtProfileGit" class="dttProfilerInfoGit ipsClearfix" data-ipsdtprofilergit data-ipsdtprofilergit-url="{$info['git_url']}">
            <div class="dttProfilerInfoGitLoading ipsLoading ipsLoading_tiny"></div>
        </div>
        {{endif}}
    </div>
    {{endif}}
</div>
<div class="dtProfilerPlaceHolder">
</div>
