<ips:template parameters="$time, $memory, $files, $templates, $database, $cache, $logs, $extra, $info, $environment, $debug, $executions,$myApps"/>
{template="myapps" group="bar" location="front" app="toolbox" params="$info,$myApps"}

<div id="dtProfilerBarContainer" class="dtProfilerBar">
    <ul class="ipsList_reset dtProfilerBar_list ipsClearfix" data-ipsdtprofiler{{if settings.dtprofiler_enable_debug && settings.dtprofiler_enable_debug_ajax }} data-ipsdtprofilerdebug data-url="{url='app=toolbox&module=bt&controller=bt' base='front'}"{{endif}}>
        {{if $time }}
        <li id="elProfileTimeLog" title="total time" class="isParent dtProfileFirst dtProfilerTime" data-ipstooltip>
            <i class="fa fa-server"></i> {$time['total']}ms <i class="fa fa-angle-up dtprofilearrow"></i>
        </li>
        <ul id="elProfileTimeLog_list" class="ipsList_reset ipsHide dtProfilerBar_cache">
            <li>
                <a>
                    Complete Execution: {$time['total']}ms
                </a>
            </li>
            <li>
                <a>
                    Framework Execution: {$time['framework']}ms
                </a>
            </li>
            <li>
                <a>
                    Profiler Execution: {$time['profiler']}ms
                </a>
            </li>
        </ul>
        {{endif}}

        {{if $executions }}
        {$executions|raw}
        {{endif}}

        {{if $memory }}
        {$memory|raw}
        {{endif}}

        {{if $files }}
        {$files|raw}
        {{endif}}

        {{if $database }}
        {$database|raw}
        {{endif}}

        {{if $cache }}
        {$cache|raw}
        {{endif}}

        {{if $environment }}
        {$environment|raw}
        {{endif}}

        {{if $templates }}
        {$templates|raw}
        {{endif}}

        {{if $logs }}
        {$logs|raw}
        {{endif}}

        {{if isset( $info['sources']) }}
        <li class="isParent dtProfileFirst">
            <a id="elProfileSources" href="#elProfileSources_menu" title="Sources" class=" " data-ipstooltip data-ipsmenu>
                Sources <i class="fa fa-angle-up"></i>
            </a>
            <ul id="elProfileSources_menu" class="ipsMenu ipsMenu_auto ipsMenu_wide ipsList_reset ipsHide">
                {{foreach $info['sources'] as $key => $val }}
                <li class="ipsMenu_item">
                    <a href="{$val['url']}" data-ipsDialog data-ipsDialog-destructOnClos="true" >
                        {$val['name']}
                    </a>
                </li>
                {{endforeach}}
            </ul>
        </li>
        {{endif}}

        {{if \IPS\Settings::i()->dtprofiler_use_console }}
        <li id="elProfileConsoleLog" class="isParent dtProfileFirst dtProfilerConsole">
            <i class="fa fa-terminal"></i> Console
            (<span class="dtprofilerCount" data-count="0">0</span>)
            <i class="fa fa-angle-up dtprofilearrow"></i>
        </li>
        <ul id="elProfileConsoleLog_list" class="ipsList_reset ipsHide dtProfilerBar_generic dtProfilerMaxWidth">
            <li class="notme ipsClearfix">
                Console Log <div class="dtProfilerClearConsoleLog ipsCursor_default ipsPos_right" data-clear> Clear </div>
            </li>
        </ul>
        {{endif}}
        {{if $debug }}
        {$debug|raw}
        {{endif}}

        {{if $extra }}
        {$extra|raw}
        {{endif}}
    </ul>
    {{if $info }}
    <div class="dtProfilerInfoBar">
        {{foreach $info['other'] as $key => $inf }}
        <div>{$key} : {$inf|raw}</div>
        {{endforeach}}

        {{if settings.dtprofiler_git_data || settings.dtprofiler_show_changes}}
        <div id="el_dtProfileGit" class="dttProfilerInfoGit ipsClearfix" data-ipsdtprofilergit data-ipsdtprofilergit-url="{$info['git_url']}">
            <div class="dttProfilerInfoGitLoading ipsLoading ipsLoading_tiny"></div>
        </div>
        {{endif}}
    </div>
    {{endif}}
</div>
<div class="dtProfilerPlaceHolder">
</div>