<ips:template parameters=""/>
<div id="elDtProfilerDiffs" class="ipsPadding ipsClearfix" data-ipstoolboxtoyboxdiffs>

    <div class="ipsGrid">
        <div class="ipsGrid_span6">
            <h4>Source 1</h4>
            <button class="ipsPos_right ipsButton ipsButton_veryVerySmall ipsButton_primary" data-clear="#source1">X</button>
            <textarea id="source1" class="text">Hello World!
foobar!</textarea>
        </div>
        <div class="ipsGrid_span6">
            <h4>Source 2</h4>
            <button class="ipsPos_right ipsButton ipsButton_veryVerySmall ipsButton_primary" data-clear="#source2">X</button>
            <textarea id="source2">Whatever World!
foobar!</textarea>
        </div>
    </div>
    <h4>Diffs</h4>
    <div id="diffs"></div>
</div>