<ips:template parameters="$form,$lorem"/>
<div class="ipsPadding ipsClearfix" data-ipstoolboxtoyboxlorem>
    {$form|raw}
    <div class="ipsClearfix">
    <button class="ipsPos_right ipsButton ipsButton_veryVerySmall ipsButton_primary" data-copy>
        <i class="fa fa-copy"></i>
    </button>
    <button class="ipsPos_right ipsButton ipsButton_veryVerySmall ipsButton_primary ipsMargin_right:half" data-generate>Generate</button>
    </div>
    <div class="ipsMargin_top" id="elLoremContainer">{$lorem|raw}</div>
</div>