<ips:template parameters="$appKey, $menus, $module, $controller,$start, $active = null, $content=null"/>

<div class="ipsPadding ipsClearfix dtProfilerDevCenterTabs">
    <h1>
        Application: {$appKey}
    </h1>
    <div class="ipsColumn ipsColumn_medium ipsTabs dtProfilerDevCenter ipsPadding_bottom:half" id="elTabs_{$controller}_{$appKey}_tabs" data-ipstabbar data-ipstabbar-contentarea="#elTabs_{$controller}_{$appKey}_tabs_content" data-ipstabbar-defaultTab="#elTab_{$controller}_{$appKey}_tab_{{if $active === null}}{$start}{{else}}{$active}{{endif}}" data-ipstabbar-updateURL="false">
        <a href="#elTabs_{$controller}_{$appKey}_tabs" data-action="expandTabs"><i class="fa fa-caret-down"></i></a>
        <ul role="tablist" class="ipsList_reset">
            {{foreach $menus as $m}}
            <li>
                <a href='{url="app=toolbox&module={$module}&controller={$controller}&appKey={$appKey}&do={$m}"}' id="elTab_{$controller}_{$appKey}_tab_{$m}" class="ipsTabs_item" role="tab">
                    {lang="dtdevplus_menu_title_{$m}"}
                </a>
            </li>
            {{endforeach}}
        </ul>
    </div>
    <div class="ipsColumn ipsColumn_fluid" id="elTabs_{$controller}_{$appKey}_tabs_content">
        {{if $active !== null}}
        <div id="ipsTabs_elTabs_{$controller}_{$appKey}_tabs_elTab_{$controller}_{$appKey}_tab_{$active}_panel" class="ipsTabs_panel" aria-labelledby="elTab_{$controller}_{$appKey}_tab_{$active}" aria-hidden="false" animating="false">
            {$content|raw}
        </div>
        {{endif}}
    </div>

</div>
