<ips:template parameters="$output,bool $show=false, ?\IPS\Http\Url $download = null, ?\IPS\Http\Url $analyze=null"/>
<div class="ipsPadding ipsBox">
    {$output|raw}
    {{if $show}}
    <div class="ipsBorder_top ipsPadding ipsType_center">
        <a href='{$analyze}' class="ipsButton ipsButton_large ipsButton_primary">Reanalyze</a>
        <a href='{$download}' class="ipsButton ipsButton_large ipsButton_primary">Build</a>
    </div>
    {{endif}}
</div>

