<ips:template parameters="$output,bool $show=false, ?\IPS\Http\Url $download = null, ?\IPS\Http\Url $analyze=null,string $title = ''"/>
<div class="ipsPadding ipsBox">
    <h1>{$title|raw}</h1>
    {$output|raw}
    {{if $show}}
    <div class="ipsBorder_top ipsPadding ipsType_center">
        <a href='{$analyze}' class="ipsButton ipsButton_large ipsButton_primary">Reanalyze</a>
        <a href='{$download}' class="ipsButton ipsButton_large ipsButton_primary">Build</a>
    </div>
    {{endif}}
</div>

