<ips:template parameters="$lists, $count"/>
<li id="elProfileQueryLog" title="Query Log" class="isParent dtProfileFirst dtProfilerQueryLog" data-ipstooltip>
    <i class="fa fa-database"></i> Query Log ({$count}) <i class="fa fa-angle-up dtprofilearrow"></i>
</li>
<ul id="elProfileQueryLog_list" class="ipsList_reset ipsHide dtProfilerBar_database dtProfilerMaxWidth">
    {{foreach $lists as $list }}
    <li>
        <div class="ipsPad">
        <a href="#" data-ipsdialog data-ipsdialog-content="#{$list['id']}" data-ipsdialog-title="SQL Query">
            {{if $list['server'] }}
            Server: {$list['server']}<br>
            {{endif}}
            {{if $list['time'] !== null}}Execution Time: {$list['time']}ms<br>{{endif}}
            {{if $list['mem'] !== null}}Memory: {$list['mem']}<br>{{endif}}
            <code class="prettyprint lang-sql">{$list['query']|raw}</code>
        </a>
            <div id="{$list['id']}" class="ipsHide ipsPad">
                {{if $list['server'] }}
                Server: {$list['server']}<br>
                {{endif}}
                {{if $list['time'] !== null}}Execution Time: {$list['time']}ms<br>{{endif}}
                {{if $list['mem'] !== null}}Memory: {$list['mem']}<br>{{endif}}
                <code class="prettyprint lang-sql">
                {$list['query']|raw}
                </code>
                {{if $list['code'] === true}}
                <br>
                <pre class="prettyprint lang-php">
                    {$list['bt']|raw}
                </pre>
                {{else}}
                <div class="ipsMargin_top:half">
                {$list['bt']|raw}
                </div>
                {{endif}}
            </div>
        </div>
    </li>
    {{endforeach}}
</ul>
