<ips:template parameters="$key,$value"/>
<div class="ipsColumns">
    <div class="ipsColumn ipsColumn_wide">{$key|raw}</div>
    <div class="ipsColumn ipsColumn_fluid">
        {{if \is_array($value) }}
        <div data-ipstoolboxtoyboxprettyprint data-ipstoolboxtoyboxprettyprint-depth="2">
            {{$vv = json_encode($value);}}
            {$vv|raw}
        </div>
        {{else}}
        {expression="(new \IPS\toolbox\Profiler\Dumper)->type($value)" raw="true"}
        {{endif}}
    </div>
</div>
